[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "pyfed"
authors = [{name = "Amirreza Sokhankhosh", email = "amirreza.sokhankhosh@gmail.com"}]
dynamic = ["version", "description"]